### PR TITLE
Update interface.md

### PR DESCRIPTION
**Pull request by ellenbroadman**
Typos and suggest adding missing information

### CODE REVIEW

**Review by sethgagnon — CHANGES_REQUESTED** [review]
Looks like you are still working on this as there are questions in line 14

**Comment by ellenbroadman** [comment]
I do not know the answers so hope someone who does can edit.  Sorry I keep
forgetting to choose dev.  Will fix those.

**Comment by sethgagnon** [comment]
Ok. We will need someone to review before we merge to dev

**Comment by ellenbroadman** [comment]
Thanks so much.  Would like someone more expert to review anyway since I am
not even using iAPS and a complete novice.

**Comment by ellenbroadman** [comment]
Hi Seth,

I am reading through the IAPS documents again and had some suggestions. But
when I click on the Edit on Github tab, and  Dev, I do not have a pencil to
make changes.  Has the procedure for submitting suggested edits changed? If
so, please send directions. Thank you.

Ellen Broadman

**Comment by sethgagnon** [comment]
No it’s the same process. You do not have the ability to edit directly in dev, which is why you don’t see the edit option. You can fork the docs GitHub repo and then make changes in your own repo and send a PR to merge the changes from your own branch to dev

--
Seth

**Comment by ellenbroadman** [comment]
Would it be helpful if I simplified the language since many people are translating into other languages?  I will send some examples to see if you think this is helpful before doing more.

**Comment by ellenbroadman** [comment]
I have simplified some of the language in Loop Docs and Miroslava Calegari
(Slovakia/Italy) and Dan H. Moody (from Germany) said they found this
helpful.  But do not want to create issues or work that anyone feels is
unnecessary.

**Comment by ellenbroadman** [comment]
Thought about this some more and decided the language is clear enough.  If
you find people are having issues with translation, please let me know and
am happy to simplify.

**Pull request merged**
