### PR TITLE
Update smbsettings.md

### PR DESCRIPTION
**Pull request by pheltzel**
This is a suggested edit to clarify the purpose of the "Enable SMB With High BG" setting, and make the connection clearer to the "… When Blood Glucose is Over (mg/dl)" setting. The documentation, as written, doesn't make the connection clear. There's a line between them in the interface, which could suggest they aren't connected and the elipsis before the next setting could mean it's connected to all the SMB settings. Discussed on Discord Jon Björn said: "Yes, I’ve thought many times about removing this new setting." The feature itself can override others, like scheduling when SMBs are off in a profile.  It also seems in conflict with the Threshold Setting, which I think it what most users would be attempting to do--not get insulin below a certain BG level. Jon also said: "The 'Enable SMB with High BG' is causing much confusion. I would suggest to all to not use this setting. Because it overrides also the temp target intention If we should keep this setting in iAPS we need to add a warning and a detailed description." [I may not have formatted the suggested change right, regrets]

### CODE REVIEW

**Comment by MikePlante1** [comment]
@Jon-b-m Sorry to tag you in documentation, but was it the "Enable SMB with High BG" setting you were considering removing? I wasn't sure if it was that or the "Schedule when SMBs are Off" setting you were talking about.

**Comment by pheltzel** [comment]
My understanding was that you can enter a BG number in “….When Blood
Glucose Is Over:” and still get an SMB when you are below that number, if
one of the other conditions in the SMB Settings area is met.

Setting a BG target under Dynamic ISF/Threshold Setting or scheduling a
time when you want SMBs off in a profile should work however, to avoid
unwanted doses.

The reason this change was suggested is because a user may think they won’t
get a dose below this set number — and they can. The setting itself, rather
than the way it’s described seems to be a problem.

I’ve spent some time in Discord and believe the way I’ve written this was
confirmed. Just let me know if I’m incorrect, thank you.



Paul Heltzel

http://heltzel.pressfolios.com/
https://www.linkedin.com/in/paul-heltzel-9175b61/

**Comment by MikePlante1** [comment]
I stand corrected. Jon confirmed your understanding of it.

**Comment by pheltzel** [comment]
Thanks for the fact check, Mike. I wouldn’t want to introduce an error.

I’m going through the docs and updating based on what I think would be the
most frequently used settings by a new user who’s trying to figure things
out.





Paul Heltzel

http://heltzel.pressfolios.com/
https://www.linkedin.com/in/paul-heltzel-9175b61/

**Comment by sethgagnon** [comment]
Are we ok to merge this then?

**Comment by MikePlante1** [comment]
I disagree with the logic, but since it's what the main developer thinks I won't stand in the way of it.

But I'd throw quotes around "(...When Blood Glucose is Over (mg/dl)" and fix the typo in "liimit"

**Comment by MikePlante1** [comment]
And maybe add the word "in" after "set below"

**Comment by pheltzel** [comment]
It should be.

I just wanted to make sure the Threshold Setting reference makes sense.

But generally I think it’s helpful to show people how to get what they want
done, like not getting dosed when you don’t want to be, vs just explaining
the setting which, to me,  is misleading and may result in a potentially
dangerous situation.











Paul Heltzel

http://heltzel.pressfolios.com/
https://www.linkedin.com/in/paul-heltzel-9175b61/

**Comment by MikePlante1** [comment]
Ideally there could be a flowchart to follow to see the order of which SMB settings supersede others, but that's for a different PR that I don't have time to research at the moment.

I don't agree with the logic of setting threshold higher to avoid SMBs at lower BGs. I want to allow iAPS to give me more insulin if it thinks I need it, but if my bg is lower and there's no COB (or carbs within the past 6 hours) I'd rather restrict the dose allowed. This setting allows this to be accomplished.

The threshold setting is not just for SMBs but for all automated insulin.

**Comment by MikePlante1** [comment]
Great, thanks!

**Comment by pheltzel** [comment]
Suggested changes above made.

Mike, I get what you mean. And by way of explaining, just as an example I've been given an SMB of almost a full unit when my BG was in the 90s, which sent me below 60 while I was sleeping. There may have been COB. My concern would be the user is also not infallible -- i.g. a parent could set a kid's settings incorrectly, especially while onboarding, maybe the ISF hasn't been dialed in yet coming over from Loop  -- and it's simply presenting a potential safety check. The user can set that safety limit or not, but at least they won't think this feature is accomplishing something it isn't designed to do.

**Comment by MikePlante1** [comment]
I think that’s a bug though, not how it’s intended to work. I base this on this exchange with @Jon-b-m 

me: `In my opinion “Schedule when SMBs are off” should mean they are off, no exceptions. And if it doesn’t guarantee it to be off then it should either be renamed, fixed, or removed.`

Jon: `It should be. If you have more details about this alleged bug please provide more details.`

**Comment by pheltzel** [comment]
Mike, this makes way more sense to me now. I can definitely see why you would want the control of setting a target for SMB alone vs. SMB/temp basals as well. If I can confirm a few things in Discord about the SMB settings so that we all have the same understanding with Jon, I think there's an opportunity to make this section of the documentation and the tooltips easier to understand. For example, one of the tooltips, "Enable SMB With High BG" references the "high BG target" which doesn't exist. It's just Target Glucose. And I'd like to get a clarification on if "...When Blood Glucose Is Over" overrides all the "Enable" settings, not just the one before it: "Enable SMB With High BG". The lines between the settings, and the elipsis after Enable SMB With High BG make it unclear what the number you're setting is controlling.

**Pull request merged**
