### PR TITLE
Update Target Ranges to Target Glucose

### PR DESCRIPTION
**Pull request by tmhastings**
Update Target Ranges section to Target Glucose in docs

### CODE REVIEW

**Comment by sethgagnon** [comment]
Just a heads up that all doc PRs need to be submitted to dev only (not main). I will update this for you

**Comment by sethgagnon** [comment]
Also magnus submitted a PR for the same changes. Can you check dev in a few minutes and see if you changes are now there with his PR? If so we can close this

**Comment by tmhastings** [comment]
Thank you for fixing my submission error. Magnus and I had discussed the
changes and both missed that each of us was working on it. His changes are
good. No need to accept mine!

Thanks!
Theresa

**Comment by sethgagnon** [comment]
Closing as these changes are in magnus's PR

**Pull request closed without merging**
