### PR TITLE
Update basalprofile.md

### PR DESCRIPTION
**Pull request by ellenbroadman**

### CODE REVIEW

**Comment by sethgagnon** [comment]
Going forward please submit prs to dev branch only

**Comment by ellenbroadman** [comment]
How do I do that?  Thanks.

**Comment by ellenbroadman** [comment]
Did you find my other prs or did they go to the wrong place.  Sorry I am
not more adept with  prs.  Still learning.

**Comment by ellenbroadman** [comment]
I figured out how to make changes in Dev.  You can ignore my email below.
Thanks.

**Comment by ellenbroadman** [comment]
Hi Seth,

I just tried to all an important edit to the docs and could not get it into
dev so put it in main.  Sorry.  But is important to let people know in the
build directions, Create App Group, that they can skip this if they have
already built Loop (as well as. iAPS) via Xcode.  Not sure if they can skip
the Add App Group to Bundle Identifiers - am asking about this.  If so will
need more edits.

**Pull request merged**
