### PR TITLE
Update carbratios.md

### PR DESCRIPTION
**Pull request by ellenbroadman**
Typos and language simplification

### CODE REVIEW

**Comment by sethgagnon** [comment]
Please submit to dev first. Thanks

**Comment by ellenbroadman** [comment]
Sorry thought I was still in dev.   And do not remember what I suggested.
Is there a way to recover my pull request?  Thanks.

**Comment by sethgagnon** [comment]
I can close this and you can issue a new one. Might be easier. There are ways to change the target branch.

**Comment by ellenbroadman** [comment]
So what do I do to find the suggestions and submit to dev?

**Comment by ellenbroadman** [comment]
I will use dev going forward.  But not sure how to find the one I put in
main by mistake to recreate the same pull request in dev.

**Comment by sethgagnon** [comment]
Go to pull requests and change the filter to closed. This will then show you all the PRs that have been closed

**Comment by ellenbroadman** [comment]
Thanks.  How do i see the content of the closed requests?

**Comment by ellenbroadman** [comment]
Thanks Seth.  This was just the info I needed and submitted a new PR in dev.

**Comment by ellenbroadman** [comment]
Hi Seth,

Where do I send suggestions for changing language in the app.  Do not
understand the “to help us guaranteed changed data”  in photo.

Do you know what this means?  Does connecting apple health help information
flow from the apple health  to IAPS or the reverse?

Thanks.

Ellen

**Comment by sethgagnon** [comment]
Changes in the app need to have PRs to the iAPS app repo: https://github.com/Artificial-Pancreas/iAPS

**Comment by ellenbroadman** [comment]
Thanks.  Do you know what this language is trying to say?  Would be helpful
to know so could suggest better language.  Thanks again.

**Comment by ellenbroadman** [comment]
Never mind.  Could not figure out how to create an appropriate PR so will
just post on Discord site that the language needs to be clarified.

**Pull request closed without merging**
