### PR TITLE
Update troubleshoot.md

### PR DESCRIPTION
**Pull request by ellenbroadman**
Minor optional ways to eliminate unnecessary words.

### CODE REVIEW

**Comment by sethgagnon** [comment]
Please change target branch to be dev. You can only push to dev.

**Comment by ellenbroadman** [comment]
Seth,

I heard there is an easy way for you to transfer these pull requests to the
dev branch.  Do you know how to do that?  If not, please just ignore the
requests.  Sorry this would take a lot of time to redo and do not have the
time right now.

Ellen

**Comment by sethgagnon** [comment]
I will look into, but please, going forward don’t submit PRs to main. I will need to end up closing them. Please double check you have the right target branch before submitting

--
Seth

**Comment by ellenbroadman** [comment]
Will try really really hard to do this.  Sorry to make your life more
complex.

**Pull request merged**
